INSERT INTO tbl_produto(nome, descricao, preco) VALUES
('CADERNO CAPA DURA HOT WHEELS','APRENDENDO MAIS RÁPIDO QUE O RELAMPAGO MARQUINHOS', 22.00),
('BORRACHA','BORRACHA FABER CASTEL APAGA AS VERGONHAS DO SEU PASSADO', 3.00),
('LAPISERA PONTA FINA','LAPISERA DE PROTAGONISTAS, PARA ESCREVER SUA PRÓRIA HISTÓRIA', 5.00),
('MARCADOR VERDE NEON','DESTAQUE PARA OS SEUS MELHORES MOMENTOS', 7.00),
('CANETA ESFOROGRÁFICA AZUL','MELHOR NÃO ARRISCAR ESSA NO ENEM', 2.00),
('CANETA ESFOROGRÁFICA PRETA','MAIS SEGURO ASSIM, BOA PROVA', 2.00),
('ESTOJO','É APENAS UM ESTOJO SIMPLES, SEJA ORGANIZADO', 10.00),
('CORRETIVO ESCOLAR','SÉRIO QUE VOCÊ AINDA USA ISSO?', 8.00),
('COLA BRANCA','COLAGENS SÃO LEGAIS, SÓ NÃO MELEQUE TUDO', 5.00),
('RÉGUA','DE TORTA JÁ BASTA TUA COLUNA', 13.00);

INSERT INTO tbl_pedido(data_ped) VALUES
('01/03/2024'),
('03/032024'),
('05/03/2024');

INSERT INTO tbl_item_pedido(cod_prod, cod_ped) VALUES
('5', '2'),
('2', '2'),
('10', '2'),
('8', '3'),
('9', '3'),
('6', '3'),
('4', '3'),
('10', '3'),
('10', '1');
